spring:
  profiles: test
  datasource:
    url: jdbc:mysql://mysql-ohio-instance1.cp1zsu6o5jlw.us-east-2.rds.amazonaws.com:3306/socialapp
    username: administrator
    password: Cha12345
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
name: yaml-Test
environment: test

server:
  port: 8008

security:
  oauth2:
    client:
      clientId: 701691307057-7m9jf1cn3g48ngk0hs97ig9m2p0ce76k.apps.googleusercontent.com
      clientSecret: O75dfJDybeO0cQJIgekdgyop
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql-ohio-instance1.cp1zsu6o5jlw.us-east-2.rds.amazonaws.com:3306/socialapp
    username: administrator
    password: Cha12345
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
name: yaml-Test
environment: production

server:
  port: 8008
